### ISSUE TITLE
Add a trim argument in the update function

### ISSUE THREAD

**Issue by robin-cls** [CNES/zcollection#3]
Hello,

I think it would be a great addition to the zcollection if we could add **trim**  argument to the zcollection.update(depth=1) function used in overlap mode. This argument would allow us to specify if our function returns the overlapped part or not

I added more details in the attached document :

[zcollection_trim_feature_request.pdf](https://github.com/CNES/zcollection/files/11294568/zcollection_trim_feature_request.pdf)

**Comment by fbriol** [comment]
Implemented in the develop branch.
