### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by Thomas-Z** [CNES/zcollection#9]
I'm working on the conda-forge packaging, here are some feedbacks:

- There is a missing dependency in setup.cfg : ``pyarrow`` (used in zcollection.indexing.abc).
- Using ``setuptools_scm`` to dynamically define the version from git tags forces us to use pypi as source. The package cannot be build from a github archive which does not contain .git information.
- I think that not having the version number writen in pyproject.toml forces setuptools to import zcollection during the packaging build step which forces us to add all the `run` dependencies to the `host` part of the ``meta.yaml``.

The conda-forge [PR is here](https://github.com/conda-forge/staged-recipes/pull/22760).
@fbriol : Could you post a comment on this PR in order for me to check the following item of the check-list:

- [x] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

**Comment by fbriol** [comment]
I modified the `setup.cfg` file to read the version number directly from the module.
